# Generated by Django 5.1.5 on 2025-02-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructorprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
