# Generated by Django 5.1.5 on 2025-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructorprofile_profile_picture_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
