# Generated by Django 5.1.5 on 2025-02-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_courses_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='files',
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='course_files/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='instructor.courses')),
            ],
        ),
    ]
