# Generated by Django 5.1.5 on 2025-02-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_courses_files_coursefiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefiles',
            old_name='files',
            new_name='file',
        ),
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=models.FileField(default=1, upload_to='course_syllabus/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='course_file/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.courses')),
            ],
        ),
    ]
