# Generated by Django 5.1.5 on 2025-02-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_rename_files_coursefiles_file_courses_syllabus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
