# Generated by Django 5.1.5 on 2025-02-10 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_remove_courses_syllabus_courses_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefiles',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
