# Generated by Django 5.1.5 on 2025-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_coursefiles_description_coursefiles_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefiles',
            name='title',
            field=models.CharField(default=1, help_text='Enter file title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursefiles',
            name='description',
            field=models.TextField(blank=True, help_text='Describe the file'),
        ),
        migrations.DeleteModel(
            name='CourseChapters',
        ),
    ]
