# Generated by Django 5.1.5 on 2025-02-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_course_is_featured_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='instructor.course'),
        ),
    ]
