# Generated by Django 5.1.5 on 2025-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentmodel_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
